services:
  webserver:
    image: ghcr.io/mausemarc/mausegibb-projekte/mom-frontend:v1
    ports:
      - "80:80"
    restart: always
    networks:
      - mom
  backend:
    image: ghcr.io/mausemarc/mausegibb-projekte/mom-backend:v1
    ports:
      - "5000:5000"
    restart: always
    environment:
      # alles platzhalter
      - DB_HOST=db #name des Datenbank service
      - DB_USER=username
      - DB_PASSWORD=timoistdaspasswort
      - DB_NAME=idk gang
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - mom
  db:
    image: mariadb:10.6.27-ubi9
    ports:
      - "3306"
    restart: always
    environment:
      # platzhalter
      MARIADB_ROOT_PASSWORD: timoistdaspasswort
      MARIADB_DATABASE: idk gang

    networks:
      - mom

networks:
  mom:
    name: mom
    driver: bridge